spring:
  application:
    name: bookoa

server:
  port: 8001
  servlet:
    context-path: /

eureka:
  instance:
    hostname: 10.211.55.7
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:123456@uk1:7001/eureka/,http://admin:123456@uk2:7002/eureka/
